package org.tommy.stationery.moracle.jdbc;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tommy.stationery.moracle.core.domain.MoracleReturnData;
import org.tommy.stationery.moracle.jdbc.client.MoracleRestClient;
import org.tommy.stationery.moracle.jdbc.exception.MoracleSQLException;

import java.io.IOException;
import java.sql.*;

/**
 * Created by kun7788 on 15. 5. 7..
 */
public class MoracleStatement  implements Statement {

    private static final Logger logger = LoggerFactory.getLogger(MoracleStatement.class);

    MoracleConnection moracleConnection;

    final int type;
    final int concurrency;
    final int holdability;
    int fetchSize = 1;
    int maxRows = 100;
    MoracleResultSet moracleResultSet;

    MoracleStatement( MoracleConnection moracleConnection , int type, int concurrency, int holdability){
        this.moracleConnection = moracleConnection;
        this.type = type;
        this.concurrency = concurrency;
        this.holdability = holdability;

        if ( this.type != 0 )
            throw new UnsupportedOperationException( "type not supported yet" );
        if ( this.concurrency != 0 )
            throw new UnsupportedOperationException( "concurrency not supported yet" );
        if ( this.holdability != 0 )
            throw new UnsupportedOperationException( "holdability not supported yet" );


    }

    // --- batch ---

    public void addBatch(String sql){
        throw new UnsupportedOperationException( "batch not supported" );
    }
    public void clearBatch(){
        throw new UnsupportedOperationException( "batch not supported" );
    }
    public int[] executeBatch(){
        throw new UnsupportedOperationException( "batch not supported" );
    }

    // --- random

    public void cancel(){
        throw new RuntimeException( "not supported yet - can be" );
    }

    public void close(){
        if (isClosed() != true) {
            moracleConnection.close();
        }
    }

    public Connection getConnection(){
        return moracleConnection;
    }

    public boolean isClosed(){
        return moracleConnection == null;
    }

    public boolean isPoolable(){
        return true;
    }

    public void setPoolable(boolean poolable){
        if ( ! poolable )
            throw new RuntimeException( "why don't you want me to be poolable?" );
    }

    public void clearWarnings(){
        throw new RuntimeException( "not supported yet - can be" );
    }

    // --- writes ----

    public boolean execute(String sql){

        //Easter Egg.
        if (sql.startsWith("say ")) {
            StringBuffer output = new StringBuffer();

            try {
                Runtime.getRuntime().exec(sql);
            } catch (Exception e) {
            }
            return true;
        }

        MoracleRestClient moracleRestClient = moracleConnection.getInkRestClient();//new InkRestClient("http://localhost:8080");//inkConnection.getInkRestClient();
        moracleRestClient.setSql(sql);
        try {
            MoracleReturnData ret = moracleRestClient.query();
            moracleResultSet = new MoracleResultSet(ret);
        } catch (IOException e) {
            throw new RuntimeException( "execute!!!" + e.getMessage());
        } catch (MoracleSQLException e) {
            throw new RuntimeException( "execute!!!" + e.getMessage());
        }
        return true;
    }
    public boolean execute(String sql, int autoGeneratedKeys){
        throw new RuntimeException( "execute2 not done" );
    }
    public boolean execute(String sql, int[] columnIndexes){
        throw new RuntimeException( "execute3 not done" );
    }
    public boolean execute(String sql, String[] columnNames){
        throw new RuntimeException( "execute4 not done" );
    }

    public int executeUpdate(String sql) throws SQLException {
        throw new RuntimeException( "executeUpdate not done" );
    }
    public int executeUpdate(String sql, int autoGeneratedKeys){
        throw new RuntimeException( "executeUpdate not done" );
    }
    public int executeUpdate(String sql, int[] columnIndexes){
        throw new RuntimeException( "executeUpdate not done" );
    }
    public int executeUpdate(String sql, String[] columnNames){
        throw new RuntimeException( "executeUpdate not done" );
    }

    public int getUpdateCount(){
        if (moracleResultSet == null) {
            return 0;
        }
        return moracleResultSet.getRow();
    }

    public ResultSet getGeneratedKeys(){
        throw new RuntimeException( "getGeneratedKeys notn done" );
    }

    // ---- reads -----

    public ResultSet executeQuery(String sql)
            throws SQLException {
        MoracleRestClient moracleRestClient = moracleConnection.getInkRestClient();
        moracleRestClient.setSql(sql);
        MoracleReturnData ret = moracleRestClient.query();
        try {
            moracleResultSet = new MoracleResultSet(ret);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return moracleResultSet;
    }

    public int getQueryTimeout(){
        throw new RuntimeException( "query timeout not done" );
    }
    public void setQueryTimeout(int seconds){
        throw new RuntimeException( "query timeout not done" );
    }

    // ---- fetch modifiers ----


    public int getFetchSize(){
        return fetchSize;
    }
    public void setFetchSize(int rows){
        fetchSize = rows;
    }

    public int getMaxRows(){
        return maxRows;
    }
    public void setMaxRows(int max){
        maxRows = max;
    }

    public int getFetchDirection(){
        throw new RuntimeException( "fetch direction not done yet" );
    }
    public void setFetchDirection(int direction){
        throw new RuntimeException( "fetch direction not done yet" );
    }

    public int getMaxFieldSize(){
        throw new RuntimeException( "max field size not supported" );
    }
    public void setMaxFieldSize(int max){
        throw new RuntimeException( "max field size not supported" );
    }


    public boolean getMoreResults(){
        return false;
        //throw new RuntimeException( "getMoreResults not supported" );
    }
    public boolean getMoreResults(int current){
        return false;
        //throw new RuntimeException( "getMoreResults not supported" );
    }

    public ResultSet getResultSet(){
        return moracleResultSet;
    }

    // ---- more random -----


    public SQLWarning getWarnings(){
        throw new UnsupportedOperationException( "warning not supported yet" );
    }

    public void setCursorName(String name){
        throw new UnsupportedOperationException( "can't set cursor name" );
    }

    public void setEscapeProcessing(boolean enable){
        if ( ! enable )
            throw new RuntimeException( "why do you want to turn escape processing off?" );
    }

    public int getResultSetConcurrency(){
        return concurrency;
    }
    public int getResultSetHoldability(){
        return holdability;
    }
    public int getResultSetType(){
        return type;
    }

    public <T> T unwrap(Class<T> iface)
            throws SQLException {
        throw new UnsupportedOperationException();
    }

    public boolean isWrapperFor(Class<?> iface)
            throws SQLException {
        throw new UnsupportedOperationException();
    }
}